"""initial database schema

Revision ID: bf4ca76fe433
Revises: 
Create Date: 2026-09-24 11:10:30.826146
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf4ca76fe433'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_events_created_at', 'agent_events', ['created_at'], unique=False)
    op.create_index('ix_agent_events_event_type', 'agent_events', ['event_type'], unique=False)
    op.create_index('ix_agent_events_family_id', 'agent_events', ['family_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_family_id', 'conversations', ['family_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_document_type', 'documents', ['document_type'], unique=False)
    op.create_index('ix_documents_family_id', 'documents', ['family_id'], unique=False)
    op.create_table('family_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('display_role', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_family_members_active', 'family_members', ['family_id', 'is_active'], unique=False)
    op.create_index('ix_family_members_family_id', 'family_members', ['family_id'], unique=False)
    op.create_index('ix_family_members_name', 'family_members', ['name'], unique=False)
    op.create_table('commitments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['family_members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_commitments_category', 'commitments', ['category'], unique=False)
    op.create_index('ix_commitments_due_date', 'commitments', ['due_date'], unique=False)
    op.create_index('ix_commitments_family_due_date', 'commitments', ['family_id', 'due_date'], unique=False)
    op.create_index('ix_commitments_family_id', 'commitments', ['family_id'], unique=False)
    op.create_index('ix_commitments_member_id', 'commitments', ['member_id'], unique=False)
    op.create_index('ix_commitments_priority', 'commitments', ['priority'], unique=False)
    op.create_index('ix_commitments_status', 'commitments', ['status'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('merchant', sa.String(length=200), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['family_members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expenses_category', 'expenses', ['category'], unique=False)
    op.create_index('ix_expenses_expense_date', 'expenses', ['expense_date'], unique=False)
    op.create_index('ix_expenses_family_date', 'expenses', ['family_id', 'expense_date'], unique=False)
    op.create_index('ix_expenses_family_id', 'expenses', ['family_id'], unique=False)
    op.create_index('ix_expenses_member_id', 'expenses', ['member_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_table('commitment_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_commitment_id', sa.UUID(), nullable=False),
    sa.Column('target_commitment_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_commitment_id <> target_commitment_id', name='ck_no_self_dependency'),
    sa.ForeignKeyConstraint(['source_commitment_id'], ['commitments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_commitment_id'], ['commitments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_commitment_id', 'target_commitment_id', 'dependency_type', name='uq_commitment_dependency')
    )
    op.create_index('ix_commitment_dependencies_source', 'commitment_dependencies', ['source_commitment_id'], unique=False)
    op.create_index('ix_commitment_dependencies_target', 'commitment_dependencies', ['target_commitment_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('commitment_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commitment_id'], ['commitments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_commitment_id', 'notifications', ['commitment_id'], unique=False)
    op.create_index('ix_notifications_family_id', 'notifications', ['family_id'], unique=False)
    op.create_index('ix_notifications_read', 'notifications', ['family_id', 'is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_read', table_name='notifications')
    op.drop_index('ix_notifications_family_id', table_name='notifications')
    op.drop_index('ix_notifications_commitment_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_commitment_dependencies_target', table_name='commitment_dependencies')
    op.drop_index('ix_commitment_dependencies_source', table_name='commitment_dependencies')
    op.drop_table('commitment_dependencies')
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.drop_index('ix_messages_conversation_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_expenses_member_id', table_name='expenses')
    op.drop_index('ix_expenses_family_id', table_name='expenses')
    op.drop_index('ix_expenses_family_date', table_name='expenses')
    op.drop_index('ix_expenses_expense_date', table_name='expenses')
    op.drop_index('ix_expenses_category', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('ix_commitments_status', table_name='commitments')
    op.drop_index('ix_commitments_priority', table_name='commitments')
    op.drop_index('ix_commitments_member_id', table_name='commitments')
    op.drop_index('ix_commitments_family_id', table_name='commitments')
    op.drop_index('ix_commitments_family_due_date', table_name='commitments')
    op.drop_index('ix_commitments_due_date', table_name='commitments')
    op.drop_index('ix_commitments_category', table_name='commitments')
    op.drop_table('commitments')
    op.drop_index('ix_family_members_name', table_name='family_members')
    op.drop_index('ix_family_members_family_id', table_name='family_members')
    op.drop_index('ix_family_members_active', table_name='family_members')
    op.drop_table('family_members')
    op.drop_index('ix_documents_family_id', table_name='documents')
    op.drop_index('ix_documents_document_type', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_conversations_family_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_agent_events_family_id', table_name='agent_events')
    op.drop_index('ix_agent_events_event_type', table_name='agent_events')
    op.drop_index('ix_agent_events_created_at', table_name='agent_events')
    op.drop_table('agent_events')
    op.drop_table('families')
    # ### end Alembic commands ###